### PR TITLE
Random now returns data, and update node version

### PR DESCRIPTION
**Pull request by alexkilgour**
- Random route now returns data with the redirect instead of just the slug
- Update the required Node version because of use of Array.Prototype.Find in model/venue.js

### CODE REVIEW

**Comment by nickcall** [comment]
👍

**Comment by andrewmee** [comment]
Worth adding the supported node versions to the packages.js engines field?

**Comment by alexkilgour** [comment]
good idea

**Comment by alexkilgour** [comment]
done

**Pull request merged**
